export const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const nameRegex = /^[A-Za-z\s]+$/;
export const userNameRegex = /^[A-Za-z0-9]+$/;

export const STATUS_OPTIONS = [
  "Backlog",
  "Proposed",
  "Needs Refinement",
  "In Refinement",
  "Ready To Commit",
  "Sprint Ready",
];

export const STORY_POINTS_OPTIONS = [1, 2, 3, 5, 8, 13, 21];

export const FIELD_VISIBILITY = {
  Backlog: {
    acceptanceCriteria: false,
    storyPoints: false,
    bv: false,
    refinementSessionScheduled: false,
    groomed: false,
    dependencies: false,
    sessionDocumented: false,
    refinementDependencies: false,
    teamApproval: false,
    poApproval: false,
    sprintCapacity: false,
    skillsAvailable: false,
    teamCommits: false,
    tasksIdentified: false,
  },
  Proposed: {
    acceptanceCriteria: true,
    storyPoints: false,
    bv: true,
    refinementSessionScheduled: false,
    groomed: false,
    dependencies: false,
    sessionDocumented: false,
    refinementDependencies: false,
    teamApproval: false,
    poApproval: false,
    sprintCapacity: false,
    skillsAvailable: false,
    teamCommits: false,
    tasksIdentified: false,
  },
  "Needs Refinement": {
    acceptanceCriteria: true,
    storyPoints: false,
    bv: true,
    refinementSessionScheduled: true,
    groomed: true,
    dependencies: true,
    sessionDocumented: true,
    refinementDependencies: false,
    teamApproval: false,
    poApproval: false,
    sprintCapacity: false,
    skillsAvailable: false,
    teamCommits: false,
    tasksIdentified: false,
  },
  "In Refinement": {
    acceptanceCriteria: true,
    storyPoints: false,
    bv: true,
    refinementSessionScheduled: true,
    groomed: true,
    dependencies: true,
    sessionDocumented: true,
    refinementDependencies: true,
    teamApproval: true,
    poApproval: true,
    sprintCapacity: false,
    skillsAvailable: false,
    teamCommits: false,
    tasksIdentified: false,
  },
  "Ready To Commit": {
    acceptanceCriteria: true,
    storyPoints: true,
    bv: true,
    refinementSessionScheduled: true,
    groomed: true,
    dependencies: true,
    sessionDocumented: true,
    refinementDependencies: true,
    teamApproval: true,
    poApproval: true,
    sprintCapacity: true,
    skillsAvailable: true,
    teamCommits: true,
    tasksIdentified: true,
  },
  "Sprint Ready": {
    acceptanceCriteria: true,
    storyPoints: true,
    bv: true,
    refinementSessionScheduled: true,
    groomed: true,
    dependencies: true,
    sessionDocumented: true,
    refinementDependencies: true,
    teamApproval: true,
    poApproval: true,
    sprintCapacity: true,
    skillsAvailable: true,
    teamCommits: true,
    tasksIdentified: true,
  },
};

export const getVisibleFields = (status) => {
  return FIELD_VISIBILITY[status] || FIELD_VISIBILITY["Backlog"];
};
